version: "3.8"

services:
  backend:
    build: ./backend  # Usa el Dockerfile del backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Montar todo el backend para evitar problemas
      - /app/node_modules  # Evitar sobreescritura de módulos
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/sg-ssta
      DATABASE_URL: "postgresql://postgres:Hugo2025@postgres:5432/portal_sg_ssta"
      JWT_SECRET: hugo_2025_seguro
      PORT: 3000
    restart: unless-stopped
    command: npm run dev  # Asegúrate de que este comando sea correcto

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/frontend-app:/app
      - /app/node_modules  # Evita problemas con los módulos
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    command: >
      sh -c "npm install --force && npm start"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hugo2025
      POSTGRES_DB: portal_sg_ssta
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mongo-data:
  postgres-data:
