version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src  # Solo montar código fuente
      - /app/node_modules  # Evitar sobreescritura de módulos
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/sg-ssta  # ✅ Mapa en lugar de lista
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/frontend-app:/app
      - /app/node_modules  # Evita problemas con los módulos
    environment:
      CHOKIDAR_USEPOLLING: "true"  # ✅ Corrección de indentación
    command: npm start

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
